PortFolioProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include ("main.urls")),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path, include
from . import views

app_name = "port"

urlpatterns = [
    path("" , views.index , name= 'index'),
    path("about/" , views.about , name= 'about'),
    path("resume/" , views.resume , name= 'resume'),
    path("portfolio/" , views.portfolio , name= 'portfolio'),
    path("services/" , views.services , name= 'services'),
    path("contact/" , views.contact , name= 'contact'),
    path('pdf-page/', views.pdf_page, name='pdf_page'),
] 

main/models.py
from django.db import models
from datetime import datetime,date

# Create your models here.
def age(year, month, day):
    today = date.today()
    age = today.year - year - ((today.month, today.day) < (month, day))
    return age



class Profile(models.Model):

    name                = models.CharField(max_length=255)
    job_title           = models.CharField(max_length=255)
    summary             = models.CharField(max_length=255)
    father_name         = models.CharField(max_length=255)
    mother_name         = models.CharField(max_length=255)
    date_of_birth       = models.DateField()
    gender              = models.CharField(max_length=255)
    mobile_number       = models.CharField(max_length=12)
    email               = models.EmailField()
    marital_status      = models.CharField(max_length=255)
    nationality         = models.CharField(max_length=255)
    nid_no              = models.CharField(max_length=255)
    religion            = models.CharField(max_length=255)
    permanent_address   = models.TextField()
    present_address     = models.TextField()
    present_salary      = models.IntegerField()
    expected_salary     = models.IntegerField()
    preferred_job       = models.CharField(max_length=255, null=True, blank=True)
    carrieer_obj        = models.TextField()
    current_degree      = models.CharField(max_length=12)
    freelance           = models.BooleanField(default=True)
    image1              = models.ImageField(upload_to='upload/profile')
    image2              = models.ImageField(upload_to='upload/profile', null= True,blank=True)
    image3              = models.ImageField(upload_to='upload/profile', null= True,blank=True)
    video               = models.FileField(upload_to='upload/video', null= True,blank=True)

    def __str__(self):
        return self.name
    

    def main_job_title(self):
        return self.job_title.split(",")[0]

    def age(self):
        dob = str( self.date_of_birth )
        year = int (dob.split("-")[0])
        month = int (dob.split("-")[1])
        day = int (dob.split("-")[-1])
        get_age = age(year, month, day)
        return get_age



class Education(models.Model):

    profile_name        = models.ForeignKey(Profile, on_delete=models.CASCADE)
    exam_name           = models.CharField(max_length=255)
    institute           = models.CharField(max_length=255)
    cgpa                = models.FloatField()
    passing_year        = models.CharField(max_length=255)
    major               = models.CharField(max_length=255)
    duration            = models.CharField(max_length=255)

    def __str__(self):
        return self.exam_name

class Course(models.Model):

    profile_name        = models.ForeignKey(Profile, on_delete=models.CASCADE)
    institute           = models.CharField(max_length=255)
    location            = models.CharField(max_length=255)
    start_date          = models.DateField()
    end_date            = models.DateField()
    certificate         = models.FileField(upload_to="upload/certificate" , null=True,blank=True)


class Experience(models.Model):
    profile_name        = models.ForeignKey(Profile, on_delete=models.CASCADE)
    company_name        = models.CharField(max_length=255)
    company_address     = models.CharField(max_length=255)
    start_date          = models.CharField(max_length=255)
    end_date            = models.CharField(max_length=255, blank=True, null=True)
    duties              = models.TextField(blank=True, null=True)


class Project(models.Model):
    profile_name        = models.ForeignKey(Profile, on_delete=models.CASCADE)
    project_title       = models.CharField(max_length=255)
    project_desc        = models.TextField(max_length=255)
    project_cat         = models.TextField(max_length=255)
    project_url         = models.CharField(max_length=255)
    project_image1      = models.ImageField(upload_to='upload/project',)
    project_image2      = models.ImageField(upload_to='upload/project', null= True,blank=True)
    project_image2      = models.ImageField(upload_to='upload/project', null= True,blank=True)

class Service(models.Model):
    profile_name            = models.ForeignKey(Profile, on_delete=models.CASCADE)
    services_title          = models.CharField(max_length=255)
    services_desc           = models.TextField(max_length=255)
    services_image1         = models.ImageField(upload_to='upload/services',blank=True, null=True)

class Testimonial(models.Model):
    profile_name            = models.ForeignKey(Profile, on_delete=models.CASCADE)
    test_by                 = models.CharField(max_length=255)
    test_company            = models.CharField(max_length=255)
    test_desig              = models.CharField(max_length=255)
    testimonial             = models.TextField()
    test_image              = models.ImageField(upload_to='upload/testimonial',blank=True, null=True)

main/views.py
from django.shortcuts import render
from .models import Profile, Education, Course, Experience,Project,Service,Testimonial 
# Create your views here.
def index(request):
    profile = Profile.objects.get(pk = 1)
    main_job_title = profile.main_job_title
    context = {"profile" : profile , "main_job_title" : main_job_title}

    return render(request, 'main/home.html', context)

def about(request):

    profile = Profile.objects.get(pk = 1)
    main_job_title = profile.main_job_title
    age = profile.age
    context = {"profile" : profile , "main_job_title" : main_job_title, "age" : age}
    return render(request, 'main/about.html', context)

def resume(request):
    return render(request, 'main/resume.html')

def portfolio(request):
    return render(request, 'main/portfolio.html')

def services(request):
    return render(request, 'main/services.html')

def contact(request):
    return render(request, 'main/contact.html')


def pdf_page(request):
    return render(request, 'main/resume.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Bashar</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'  %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
{% include 'includes/header.html' %}
  <!-- End Header -->

<main id="main">

{% block content %}


{% endblock  %}

</main>


  <!-- ======= Footer ======= -->

  {% include 'includes/footer.html' %}
  <!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/typed.js/typed.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/progressbar.js/1.0.1/progressbar.min.js"></script>


  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/baseNext.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>iPortfolio Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png'  %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: iPortfolio - v3.10.0
  * Template URL: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Mobile nav toggle button ======= -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>

  <!-- ======= Header ======= -->
{% include 'includes/header.html' %}
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->

{% include 'includes/hero.html' %}
  <!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    {% include 'includes/about.html' %}
    <!-- End About Section -->

    <!-- ======= Facts Section ======= -->
    {% include 'includes/facts.html' %}
    
    <!-- End Facts Section -->

    <!-- ======= Skills Section ======= -->

    {% include 'includes/skills.html' %}
    <!-- End Skills Section -->

    <!-- ======= Resume Section ======= -->
    {% include 'includes/resume.html' %}

    <!-- End Resume Section -->

    <!-- ======= Portfolio Section ======= -->
    {% include 'includes/portfolio.html' %}
    <!-- End Portfolio Section -->

    <!-- ======= Services Section ======= -->

    {% include 'includes/services.html' %}
    <!-- End Services Section -->

    <!-- ======= Testimonials Section ======= -->
    {% include 'includes/testimonials.html' %}
    <!-- End Testimonials Section -->

    <!-- ======= Contact Section ======= -->

    {% include 'includes/contact.html' %}
    <!-- End Contact Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->

  
  <!-- End  Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/typed.js/typed.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/includes/footer.html
<footer id="footer">
    <div class="container">
      <div class="copyright">
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/iportfolio-bootstrap-portfolio-websites-template/ -->
       <h6> Powered by Django </h6>
        Designed by <a href="#">Bashar</a>
      </div>
    </div>
  </footer>

templates/includes/header.html
{% load static %}

<header id="header">
    <div class="d-flex flex-column">

      <div class="profile">
        <img src="{% static 'assets/img/profile-img.jpg' %}" alt="" class="img-fluid rounded-circle">
        <h1 class="text-light"><a href="index.html">Abul Bashar</a></h1>
        <div class="social-links mt-3 text-center">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>

      <nav id="navbar" class="nav-menu navbar">
        <ul>
          <li><a href="{% url 'port:index' %}" class="nav-link scrollto {% if request.path == "/"  %} active {% endif %}"><i class="bx bx-home"></i> <span>Home</span></a></li>
          <li><a href="{% url 'port:about' %}" class="nav-link scrollto {% if request.path == "/about/"  %} active {% endif %}" ><i class="bx bx-user"></i> <span>About</span></a></li>
          <li><a href="{% url 'port:resume' %}" class="nav-link scrollto {% if request.path == "/resume/"  %} active {% endif %}" ><i class="bx bx-file-blank"></i> <span>Resume</span></a></li>
          <li><a href="{% url 'port:portfolio' %}" class="nav-link scrollto {% if request.path == "/portfolio/"  %} active {% endif %}" ><i class="bx bx-book-content"></i> <span>Portfolio</span></a></li>
        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header>
  

templates/main/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<section id="about" class="about">

    <div class="container">

      <div class="section-title">
        <h2>About</h2>
        <p>To secure a challenging position as a <b> Data Analyst </b> in a dynamic organization where I can utilize my technical skills and analytical expertise to drive business growth, optimize operations, and contribute to the development of innovative solutions.</p>
      </div>

      <div class="row">
        <div class="col-lg-4" data-aos="fade-right">
          <img src="{% static 'assets/img/profile-img.jpg' %}" class="img-fluid" alt="">
        </div>
        <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
          <h3>Data Analyst & Automation </h3>
          <p class="fst-italic">
            
          </p>
          <div class="row">
            <div class="col-lg-6">
              <ul>
                <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <span>{{profile.date_of_birth}}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>www.bashar.pythonanywhere.com</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>+880-{{profile.mobile_number}}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>Gazipur</span></li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul>
                <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>{{profile.age}}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>{{profile.current_degree}}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Email:</strong> <span>{{profile.email}}</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong> <span> {% if  profile.freelance %} Available  {% else %} Not Available {% endif %} </span></li>
              </ul>
            </div>
          </div>
          <p>
            I am a highly skilled with a strong background in data analysis and a passion for using technology to drive business success. </br> </br>
             With 5 years of experience in the industry,
             I have developed a deep understanding of data-driven decision making, 
             and I am adept at using a wide range of analytical tools such as <b> Python , Pandas, Power BI with DAX, Excel , Matplotlib, Streamlit
              </b> and so on and techniques to uncover valuable insights and drive process improvement. </br></br>

Throughout my career, I have been recognized for my ability to work collaboratively with cross-functional teams and communicate complex technical concepts to non-technical stakeholders. I am committed to staying up-to-date with the latest industry trends and best practices, and I am always looking for new and innovative ways to leverage technology to solve business problems.

In addition to my technical expertise, I am a creative problem solver with a strong attention to detail and a track record of delivering high-quality work on time and within budget. I am excited about the opportunity to apply my skills and experience to help your organization achieve its goals and drive growth in the digital age.
          </p>
        </div>
      </div>

    </div>
  </section>


{% endblock %}

templates/main/contact.html
<section id="contact" class="contact">
    <div class="container">

      <div class="section-title">
        <h2>Contact</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="row" data-aos="fade-in">

        <div class="col-lg-5 d-flex align-items-stretch">
          <div class="info">
            <div class="address">
              <i class="bi bi-geo-alt"></i>
              <h4>Location:</h4>
              <p>A108 Adam Street, New York, NY 535022</p>
            </div>

            <div class="email">
              <i class="bi bi-envelope"></i>
              <h4>Email:</h4>
              <p>info@example.com</p>
            </div>

            <div class="phone">
              <i class="bi bi-phone"></i>
              <h4>Call:</h4>
              <p>+1 5589 55488 55s</p>
            </div>

            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>
          </div>

        </div>

        <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
          <form action="forms/contact.php" method="post" role="form" class="php-email-form">
            <div class="row">
              <div class="form-group col-md-6">
                <label for="name">Your Name</label>
                <input type="text" name="name" class="form-control" id="name" required>
              </div>
              <div class="form-group col-md-6">
                <label for="name">Your Email</label>
                <input type="email" class="form-control" name="email" id="email" required>
              </div>
            </div>
            <div class="form-group">
              <label for="name">Subject</label>
              <input type="text" class="form-control" name="subject" id="subject" required>
            </div>
            <div class="form-group">
              <label for="name">Message</label>
              <textarea class="form-control" name="message" rows="10" required></textarea>
            </div>
            <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>
        </div>

      </div>

    </div>
  </section>

templates/main/facts.html
<section id="facts" class="facts">
    <div class="container">

      <div class="section-title">
        <h2>Facts</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="row no-gutters">

        <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up">
          <div class="count-box">
            <i class="bi bi-emoji-smile"></i>
            <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
            <p><strong>Happy Clients</strong> consequuntur quae</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up" data-aos-delay="100">
          <div class="count-box">
            <i class="bi bi-journal-richtext"></i>
            <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter"></span>
            <p><strong>Projects</strong> adipisci atque cum quia aut</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up" data-aos-delay="200">
          <div class="count-box">
            <i class="bi bi-headset"></i>
            <span data-purecounter-start="0" data-purecounter-end="1453" data-purecounter-duration="1" class="purecounter"></span>
            <p><strong>Hours Of Support</strong> aut commodi quaerat</p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up" data-aos-delay="300">
          <div class="count-box">
            <i class="bi bi-people"></i>
            <span data-purecounter-start="0" data-purecounter-end="32" data-purecounter-duration="1" class="purecounter"></span>
            <p><strong>Hard Workers</strong> rerum asperiores dolor</p>
          </div>
        </div>

      </div>

    </div>
  </section>

templates/main/home.html
{% extends 'base.html' %}


{% block content %}

<style>

  .rel{
    position: relative;
  }

  .bottom-text {
    position: absolute;
    bottom: 5px;
    left:0px;
    font-weight: 800;
    color: #fff

  </style>

<section id="hero" class="d-flex flex-column justify-content-center align-items-center rel">
    <div class="hero-container" data-aos="fade-in">
      <h1>{{profile.name}}</h1>
      <p>I'm <span class="typed" data-typed-items="{{profile.job_title}}"></span></p>

      
    </div>


  </section>
  

{% endblock content %}

templates/main/services.html
<section id="services" class="services">
    <div class="container">

      <div class="section-title">
        <h2>Services</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="row">
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
          <div class="icon"><i class="bi bi-briefcase"></i></div>
          <h4 class="title"><a href="">Lorem Ipsum</a></h4>
          <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
        </div>
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
          <div class="icon"><i class="bi bi-card-checklist"></i></div>
          <h4 class="title"><a href="">Dolor Sitema</a></h4>
          <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>
        </div>
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
          <div class="icon"><i class="bi bi-bar-chart"></i></div>
          <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
          <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
        </div>
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
          <div class="icon"><i class="bi bi-binoculars"></i></div>
          <h4 class="title"><a href="">Magni Dolores</a></h4>
          <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
        </div>
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
          <div class="icon"><i class="bi bi-brightness-high"></i></div>
          <h4 class="title"><a href="">Nemo Enim</a></h4>
          <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
        </div>
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
          <div class="icon"><i class="bi bi-calendar4-week"></i></div>
          <h4 class="title"><a href="">Eiusmod Tempor</a></h4>
          <p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>
        </div>
      </div>

    </div>
  </section>